### PR TITLE
simplify dockerfile

### PR DESCRIPTION
**Pull request by inductor**
- using apk upgrade is not very good for docker image stability
- merged installing libstdc++ to the other installation process
- Practically, you don't use cd in Dockerfile and use WORKDIR instead
- git init & fetch can be replaced in one command using clone

### CODE REVIEW

**Comment by inductor** [comment]
Please have a look! @lkwg82

**Comment by lkwg82** [comment]
Thx, will have a look this weekend.

**Comment by inductor** [comment]
@lkwg82 any update?

**Comment by lkwg82** [comment]
Missed to thank you for the PR

**Comment by inductor** [comment]
You're welcome. Thank you for this convenient repository! :)

**Pull request merged**
